# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 06:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('alignment', models.CharField(choices=[('N', 'Normal'), ('C', 'Council of Ricks'), ('R', 'The Rickest Rick')], default='N', max_length=1, primary_key=True, serialize=False)),
                ('badgeimg', models.ImageField(null=True, upload_to='images/badges/')),
                ('goal', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('schmeckles', models.IntegerField(default=0)),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Alignment')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descriptor', models.TextField()),
                ('goal', models.TextField()),
                ('teamimg', models.ImageField(upload_to='images/teams/')),
            ],
        ),
        migrations.AddField(
            model_name='identity',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Team'),
        ),
    ]
