# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teamname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='alignment',
            name='badgeimg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='descriptor',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamimg',
        ),
        migrations.AddField(
            model_name='alignment',
            name='badge_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/badges/'),
        ),
        migrations.AddField(
            model_name='alignment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/teams/'),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='goal',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='goal',
            field=models.TextField(null=True),
        ),
    ]
