# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('successtext', models.TextField(blank=True, null=True)),
                ('event_img', models.ImageField(blank=True, null=True, upload_to='images/events/')),
            ],
            options={
                'ordering': ('time', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revealed', models.BooleanField(default=False)),
                ('event', models.ManyToManyField(to='schedule.Event')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
