# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0002_auto_20160515_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ManyToManyField(to='schedule.Event')),
                ('user', models.ManyToManyField(to='info.Team')),
            ],
        ),
    ]
