# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('time', 'name')},
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='successtext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='revealed',
            field=models.BooleanField(default=False),
        ),
    ]
